-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 01:38:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gogomoney4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gogomoney4` ;

-- -----------------------------------------------------
-- Schema gogomoney4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gogomoney4` DEFAULT CHARACTER SET utf8 ;
USE `gogomoney4` ;

-- -----------------------------------------------------
-- Table `gogomoney4`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney4`.`category` ;

CREATE TABLE IF NOT EXISTS `gogomoney4`.`category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `gogomoney4`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney4`.`user` ;

CREATE TABLE IF NOT EXISTS `gogomoney4`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `start_balance` DOUBLE NULL DEFAULT NULL,
  `amount_to_save` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `gogomoney4`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney4`.`transaction` ;

CREATE TABLE IF NOT EXISTS `gogomoney4`.`transaction` (
  `transaction_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `transaction_user_key_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `transaction_user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `gogomoney4`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `gogomoney4`.`income`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney4`.`income` ;

CREATE TABLE IF NOT EXISTS `gogomoney4`.`income` (
  `income_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `amount` DOUBLE NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `recurring` VARCHAR(25) NULL DEFAULT 'FALSE',
  `recur_interval` VARCHAR(25) NULL DEFAULT NULL,
  `recurr_day` INT(11) NULL DEFAULT NULL,
  `recurr_count` INT(11) NULL DEFAULT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `entry_date` DATE NULL DEFAULT NULL,
  `transaction_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`income_id`),
  INDEX `in_category_key_idx` (`category_id` ASC) VISIBLE,
  INDEX `in_transaction_key_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `in_category_fkey`
    FOREIGN KEY (`category_id`)
    REFERENCES `gogomoney4`.`category` (`category_id`),
  CONSTRAINT `in_transaction_key`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `gogomoney4`.`transaction` (`transaction_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `gogomoney4`.`outcome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney4`.`outcome` ;

CREATE TABLE IF NOT EXISTS `gogomoney4`.`outcome` (
  `outcome_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `amount` DOUBLE NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `recuring` VARCHAR(25) NULL DEFAULT 'FALSE',
  `recur_interval` VARCHAR(25) NULL DEFAULT NULL,
  `recurr_day` INT(11) NULL DEFAULT NULL,
  `recurr_count` INT(11) NULL DEFAULT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `entry_date` DATE NULL DEFAULT NULL,
  `transaction_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`outcome_id`),
  INDEX `out_category_key_idx` (`category_id` ASC) VISIBLE,
  INDEX `out_transaction_key_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `out_category_fkey`
    FOREIGN KEY (`category_id`)
    REFERENCES `gogomoney4`.`category` (`category_id`),
  CONSTRAINT `out_transaction_key`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `gogomoney4`.`transaction` (`transaction_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
