-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 20:30:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gogomoney04-01
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gogomoney04-01` ;

-- -----------------------------------------------------
-- Schema gogomoney04-01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gogomoney04-01` DEFAULT CHARACTER SET utf8 ;
USE `gogomoney04-01` ;

-- -----------------------------------------------------
-- Table `gogomoney04-01`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney04-01`.`user` ;

CREATE TABLE IF NOT EXISTS `gogomoney04-01`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `start_balance` DOUBLE NULL DEFAULT NULL,
  `amount_to_save` DOUBLE NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gogomoney04-01`.`financial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gogomoney04-01`.`financial` ;

CREATE TABLE IF NOT EXISTS `gogomoney04-01`.`financial` (
  `financial_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `income_outcome` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  `recurring` VARCHAR(25) NULL DEFAULT 'FALSE',
  `recur_interval` VARCHAR(25) NOT NULL,
  `recurr_day` INT(11) NULL DEFAULT NULL,
  `recurr_count` INT(11) NULL DEFAULT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `entry_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`financial_id`),
  INDEX `in_user_key_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `in_user_fkey`
    FOREIGN KEY (`user_id`)
    REFERENCES `gogomoney04-01`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
